scala_binary(
    name = "scala_rest",
    main_class = "jpm.restapi.RestServerMain",
    visibility = ["//visibility:public"],
    deps = [
        "//examples/scala/restapi/src/main/scala/jpm/restapi",
    ]
)

scala_repl(
    name = "repl",
    visibility = ["//visibility:public"],
    deps = [
        "//examples/scala/restapi/src/main/scala/jpm/restapi",
    ]
)