# This file is autogenerated with dep2bazel, do not edit.
load("@bazel_gazelle//:deps.bzl", "go_repository")

def jaeger_go_deps():

    go_repository(
        name = "com_github_beorn7_perks",
        importpath = "github.com/beorn7/perks",
        urls = ["https://github.com/beorn7/perks/archive/3a771d992973f24aa725d07868b467d1ddfceafb.tar.gz"],
        strip_prefix = "perks-3a771d992973f24aa725d07868b467d1ddfceafb/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_codahale_hdrhistogram",
        importpath = "github.com/codahale/hdrhistogram",
        urls = ["https://github.com/codahale/hdrhistogram/archive/3a0bb77429bd3a61596f5e8a3172445844342120.tar.gz"],
        strip_prefix = "hdrhistogram-3a0bb77429bd3a61596f5e8a3172445844342120/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_crossdock_crossdock_go",
        importpath = "github.com/crossdock/crossdock-go",
        urls = ["https://github.com/crossdock/crossdock-go/archive/049aabb0122b03bc9bd30cab8f3f91fb60166361.tar.gz"],
        strip_prefix = "crossdock-go-049aabb0122b03bc9bd30cab8f3f91fb60166361/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_davecgh_go_spew",
        importpath = "github.com/davecgh/go-spew",
        urls = ["https://github.com/davecgh/go-spew/archive/346938d642f2ec3594ed81d874461961cd0faa76.tar.gz"],
        strip_prefix = "go-spew-346938d642f2ec3594ed81d874461961cd0faa76/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_golang_protobuf",
        importpath = "github.com/golang/protobuf",
        urls = ["https://github.com/golang/protobuf/archive/925541529c1fa6821df4e44ce2723319eb2be768.tar.gz"],
        strip_prefix = "protobuf-925541529c1fa6821df4e44ce2723319eb2be768/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_matttproud_golang_protobuf_extensions",
        importpath = "github.com/matttproud/golang_protobuf_extensions",
        urls = ["https://github.com/matttproud/golang_protobuf_extensions/archive/3247c84500bff8d9fb6d579d800f20b3e091582c.tar.gz"],
        strip_prefix = "golang_protobuf_extensions-3247c84500bff8d9fb6d579d800f20b3e091582c/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_opentracing_opentracing_go",
        importpath = "github.com/opentracing/opentracing-go",
        urls = ["https://github.com/opentracing/opentracing-go/archive/1949ddbfd147afd4d964a9f00b24eb291e0e7c38.tar.gz"],
        strip_prefix = "opentracing-go-1949ddbfd147afd4d964a9f00b24eb291e0e7c38/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_pkg_errors",
        importpath = "github.com/pkg/errors",
        urls = ["https://github.com/pkg/errors/archive/645ef00459ed84a119197bfb8d8205042c6df63d.tar.gz"],
        strip_prefix = "errors-645ef00459ed84a119197bfb8d8205042c6df63d/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_pmezard_go_difflib",
        importpath = "github.com/pmezard/go-difflib",
        urls = ["https://github.com/pmezard/go-difflib/archive/792786c7400a136282c1664665ae0a8db921c6c2.tar.gz"],
        strip_prefix = "go-difflib-792786c7400a136282c1664665ae0a8db921c6c2/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_prometheus_client_golang",
        importpath = "github.com/prometheus/client_golang",
        urls = ["https://github.com/prometheus/client_golang/archive/c5b7fccd204277076155f10851dad72b76a49317.tar.gz"],
        strip_prefix = "client_golang-c5b7fccd204277076155f10851dad72b76a49317/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_prometheus_client_model",
        importpath = "github.com/prometheus/client_model",
        urls = ["https://github.com/prometheus/client_model/archive/99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c.tar.gz"],
        strip_prefix = "client_model-99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_prometheus_common",
        importpath = "github.com/prometheus/common",
        urls = ["https://github.com/prometheus/common/archive/d811d2e9bf898806ecfb6ef6296774b13ffc314c.tar.gz"],
        strip_prefix = "common-d811d2e9bf898806ecfb6ef6296774b13ffc314c/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_prometheus_procfs",
        importpath = "github.com/prometheus/procfs",
        urls = ["https://github.com/prometheus/procfs/archive/8b1c2da0d56deffdbb9e48d4414b4e674bd8083e.tar.gz"],
        strip_prefix = "procfs-8b1c2da0d56deffdbb9e48d4414b4e674bd8083e/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_stretchr_testify",
        importpath = "github.com/stretchr/testify",
        urls = ["https://github.com/stretchr/testify/archive/12b6f73e6084dad08a7c6e575284b177ecafbc71.tar.gz"],
        strip_prefix = "testify-12b6f73e6084dad08a7c6e575284b177ecafbc71/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_uber_go_atomic",
        importpath = "github.com/uber-go/atomic",
        urls = ["https://github.com/uber-go/atomic/archive/8474b86a5a6f79c443ce4b2992817ff32cf208b8.tar.gz"],
        strip_prefix = "atomic-8474b86a5a6f79c443ce4b2992817ff32cf208b8/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "com_github_uber_jaeger_lib",
        importpath = "github.com/uber/jaeger-lib",
        urls = ["https://github.com/uber/jaeger-lib/archive/4267858c0679cd4e47cefed8d7f70fd386cfb567.tar.gz"],
        strip_prefix = "jaeger-lib-4267858c0679cd4e47cefed8d7f70fd386cfb567/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "org_uber_go_atomic",
        importpath = "go.uber.org/atomic",
        urls = ["https://github.com/uber-go/atomic/archive/54f72d32435d760d5604f17a82e2435b28dc4ba5.tar.gz"],
        strip_prefix = "atomic-54f72d32435d760d5604f17a82e2435b28dc4ba5/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "org_uber_go_multierr",
        importpath = "go.uber.org/multierr",
        urls = ["https://github.com/uber-go/multierr/archive/3c4937480c32f4c13a875a1829af76c98ca3d40a.tar.gz"],
        strip_prefix = "multierr-3c4937480c32f4c13a875a1829af76c98ca3d40a/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "org_uber_go_zap",
        importpath = "go.uber.org/zap",
        urls = ["https://github.com/uber-go/zap/archive/eeedf312bc6c57391d84767a4cd413f02a917974.tar.gz"],
        strip_prefix = "zap-eeedf312bc6c57391d84767a4cd413f02a917974/",
        build_file_proto_mode = "default",
    )

    go_repository(
        name = "org_golang_x_net",
        importpath = "golang.org/x/net",
        urls = ["https://github.com/golang/net/archive/5f9ae10d9af5b1c89ae6904293b14b064d4ada23.tar.gz"],
        strip_prefix = "net-5f9ae10d9af5b1c89ae6904293b14b064d4ada23/",
        build_file_proto_mode = "default",
    )
