scala_library(
    name = "model",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/jvm/com/typesafe/akka:akka_http_2_11",
        "//3rdparty/jvm/com/typesafe/akka:akka_http_spray_json_2_11",
    ],
)
