
go_library(
    name = "jaeger_init",
    srcs = ["jaeger_init.go"],
    importpath = "github.com/jmeagher/monorepo/tracing/jaeger",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_uber_jaeger_client_go//config:go_default_library",
        #"@com_github_uber_jaeger_lib//metrics/prometheus:go_default_library",
    ],
)
