load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "go_default_test",
    size = "small",
    srcs = ["handler_test.go"],
)

go_test(
    name = "handlers_test",
    srcs = ["handler_test.go"],
)
