scala_library(
    name = "jpm",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/maven_deps:com_twitter_finatra_finatra_http_2_11",
    ]
)
