rust_binary(
    name = "fibonacci",
    srcs = [
        "main.rs",
    ],
    deps = [
        "//examples/rust/simple/src:fibonacci",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["*"]),
)
