package(default_visibility = ["//visibility:public"])

# py_library(
#     name = "numerics",
#     srcs = [
#         "__init__.py",
#         "numerics.py",
#     ],
#     imports = [".."],
#     deps = [
#         requirement("numpy"),
#         requirement("pandas"),
#         requirement("pytz"),
#         requirement("python-dateutil"),
#         requirement("six"),
#     ],
# )

# py_test(
#     name = "numerics_test",
#     size = "small",
#     srcs = ["test/numerics_test.py"],
#     deps = [":numerics"],
# )
