scala_test(
    name = "test",
    srcs = glob(["*.scala"]),
    size = "small",
    deps = [
        "//examples/scala/restapi/src/main/scala/jpm/restapi",
        "//3rdparty/jvm/com/typesafe/akka:akka_http_spray_json_2_11",
        "//3rdparty/jvm/com/typesafe/akka:akka_http_testkit_2_11",
    ],
)
