# rust_library(
#     name = "fibonacci",
#     srcs = ["fibonacci.rs"],
#     visibility = ["//visibility:public"],
# )

# rust_test(
#     name = "fibonacci_test",
#     deps = [":fibonacci"],
#     size = "small",
# )

# rust_doc(
#     name = "fibonacci_doc",
#     dep = ":fibonacci",
# )

# rust_doc_test(
#     name = "fibonacci_doc_test",
#     dep = ":fibonacci",
#     size = "small",
# )

filegroup(
    name = "srcs",
    srcs = glob(["*"]),
)
