scala_library(
    name = "restapi",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_typesafe_akka_akka_http_2_11",
        "@maven//:com_typesafe_akka_akka_http_spray_json_2_11",
    ],
)
