
scala_library(
    name = "restapi",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
#        "//3rdparty/jvm/com/twitter:finagle_http_2_11",
#        "//3rdparty/jvm/com/twitter:twitter_server",
        "//3rdparty/jvm/com/twitter/finatra:finatra_http_2_11",
#        "//3rdparty/jvm/com/twitter/finatra:finatra_scalap_compiler_deps_2_11",
#        "//3rdparty/jvm/com/twitter/finatra:finatra_utils",
#        "//3rdparty/jvm/com/twitter/inject:inject_core_2_11",
    ],
)
