on: push
name: My Action
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel build //...
    - run: bazel test //...
